import { QuestionData } from "@/app/GlobalRedux/Features/questionSlice";

export const addEng: QuestionData[] = [
  {
    id: 1,
    question: "Athens had _________ the Greek-states against Persians.",
    section:
      "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
    option: {
      a: "refused to help",
      b: "wanted to fight",
      c: "intervened on behalf",
      d: "given orders to fight",
    },
    questionNub: 1,
    hasPassage: 0,
    category: "comprehension",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 2,
    question:
      "Darius took drastic steps to __________ the rebellious Athenians.",
    section:
      "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
    option: { a: "irritate", b: "weaken", c: "destroy", d: "calm" },
    questionNub: 2,
    hasPassage: 0,
    category: "comprehension",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 3,
    question: "&nbsp;Their participation _________to the Athenians.",
    section:
      "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
    option: {
      a: "gave hope",
      b: "gave honour",
      c: "gave comfort",
      d: "gave strength",
    },
    questionNub: 3,
    hasPassage: 0,
    category: "comprehension",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 4,
    question:
      "The people of Delos did not want to __________ the conquest of Greece",
    section:
      "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
    option: {
      a: "think about",
      b: "end",
      c: "encourage",
      d: "daydream about",
    },
    questionNub: 4,
    hasPassage: 0,
    category: "comprehension",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 5,
    question:
      "The Athenians were__________ by some soldiers who arrived at Plataea",
    section:
      "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
    option: {
      a: "held",
      b: "strengthened",
      c: "welcomed",
      d: "captured",
    },
    questionNub: 5,
    hasPassage: 0,
    category: "comprehension",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 6,
    question: "...1...",
    section:
      "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.<br>\n<br>\nPASSAGE IV<br>\n<br>\nWith the most profound respect to the members of the Senate, I do not think that it is within the competence of that ...1... body to pass a motion to ...2... the executive action of the President. The Senate is ...3... of the National Assembly. But it is not by itself alone the National Assembly. One can imagine the confusion, which would be created if the ...4... were to take a view diametrically opposed to that reflected in the Senate resolution. The strongest objection to the action of the Senate in passing the resolution is the fact that it constituted itself the ...5... as well as the judge of the constitutionality of the action of the President. The function of the Senate is to ...6... laws. But the Senate has no authority or ...7... to control the President in the exercise of his ...8... powers. It cannot by a mere resolution or motion give any directive to the President regarding the exercise of his powers nor can it undo what the President has done in the exercise of those powers. The only way in which the exercise of the powers of the President can be ...9... is by ...10... of the National Assembly.<br>\nAdapted from The Guardian of July 8, 1999, p. 8.",
    option: {
      a: "executive",
      b: "legislative",
      c: "judicial",
      d: "administrative",
    },
    questionNub: 6,
    hasPassage: 0,
    category: "language-registers",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 7,
    question: "...2...",
    section:
      "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.<br>\n<br>\nPASSAGE IV<br>\n<br>\nWith the most profound respect to the members of the Senate, I do not think that it is within the competence of that ...1... body to pass a motion to ...2... the executive action of the President. The Senate is ...3... of the National Assembly. But it is not by itself alone the National Assembly. One can imagine the confusion, which would be created if the ...4... were to take a view diametrically opposed to that reflected in the Senate resolution. The strongest objection to the action of the Senate in passing the resolution is the fact that it constituted itself the ...5... as well as the judge of the constitutionality of the action of the President. The function of the Senate is to ...6... laws. But the Senate has no authority or ...7... to control the President in the exercise of his ...8... powers. It cannot by a mere resolution or motion give any directive to the President regarding the exercise of his powers nor can it undo what the President has done in the exercise of those powers. The only way in which the exercise of the powers of the President can be ...9... is by ...10... of the National Assembly.<br>\nAdapted from The Guardian of July 8, 1999, p. 8.",
    option: { a: "modify", b: "nullify", c: "order", d: "enforce" },
    questionNub: 7,
    hasPassage: 0,
    category: "language-registers",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 8,
    question: "...3...",
    section:
      "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.<br>\n<br>\nPASSAGE IV<br>\n<br>\nWith the most profound respect to the members of the Senate, I do not think that it is within the competence of that ...1... body to pass a motion to ...2... the executive action of the President. The Senate is ...3... of the National Assembly. But it is not by itself alone the National Assembly. One can imagine the confusion, which would be created if the ...4... were to take a view diametrically opposed to that reflected in the Senate resolution. The strongest objection to the action of the Senate in passing the resolution is the fact that it constituted itself the ...5... as well as the judge of the constitutionality of the action of the President. The function of the Senate is to ...6... laws. But the Senate has no authority or ...7... to control the President in the exercise of his ...8... powers. It cannot by a mere resolution or motion give any directive to the President regarding the exercise of his powers nor can it undo what the President has done in the exercise of those powers. The only way in which the exercise of the powers of the President can be ...9... is by ...10... of the National Assembly.<br>\nAdapted from The Guardian of July 8, 1999, p. 8.",
    option: { a: "an anchor", b: "a portion", c: "a wing", d: "an arm" },
    questionNub: 8,
    hasPassage: 0,
    category: "language-registers",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 9,
    question: "...4...",
    section:
      "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.<br>\n<br>\nPASSAGE IV<br>\n<br>\nWith the most profound respect to the members of the Senate, I do not think that it is within the competence of that ...1... body to pass a motion to ...2... the executive action of the President. The Senate is ...3... of the National Assembly. But it is not by itself alone the National Assembly. One can imagine the confusion, which would be created if the ...4... were to take a view diametrically opposed to that reflected in the Senate resolution. The strongest objection to the action of the Senate in passing the resolution is the fact that it constituted itself the ...5... as well as the judge of the constitutionality of the action of the President. The function of the Senate is to ...6... laws. But the Senate has no authority or ...7... to control the President in the exercise of his ...8... powers. It cannot by a mere resolution or motion give any directive to the President regarding the exercise of his powers nor can it undo what the President has done in the exercise of those powers. The only way in which the exercise of the powers of the President can be ...9... is by ...10... of the National Assembly.<br>\nAdapted from The Guardian of July 8, 1999, p. 8.",
    option: {
      a: "Judiciary",
      b: "Executive Council",
      c: "House of Representatives",
      d: "National Assembly",
    },
    questionNub: 9,
    hasPassage: 0,
    category: "language-registers",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 10,
    question: "...5...",
    section:
      "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.<br>\n<br>\nPASSAGE IV<br>\n<br>\nWith the most profound respect to the members of the Senate, I do not think that it is within the competence of that ...1... body to pass a motion to ...2... the executive action of the President. The Senate is ...3... of the National Assembly. But it is not by itself alone the National Assembly. One can imagine the confusion, which would be created if the ...4... were to take a view diametrically opposed to that reflected in the Senate resolution. The strongest objection to the action of the Senate in passing the resolution is the fact that it constituted itself the ...5... as well as the judge of the constitutionality of the action of the President. The function of the Senate is to ...6... laws. But the Senate has no authority or ...7... to control the President in the exercise of his ...8... powers. It cannot by a mere resolution or motion give any directive to the President regarding the exercise of his powers nor can it undo what the President has done in the exercise of those powers. The only way in which the exercise of the powers of the President can be ...9... is by ...10... of the National Assembly.<br>\nAdapted from The Guardian of July 8, 1999, p. 8.",
    option: {
      a: "plaintiff",
      b: "attorney",
      c: "defendant",
      d: "litigant",
    },
    questionNub: 10,
    hasPassage: 0,
    category: "language-registers",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 11,
    question: "_________ is the euphemism use for Cheat notes.",
    section: 'This question is based on "The Life Changer" novel.',
    option: {
      a: "Salvation note of rescue",
      b: "note of deliverance",
      c: "holy note of rescue",
      d: "Notes of salvation",
    },
    questionNub: 11,
    hasPassage: 0,
    category: "the-life-changer",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 12,
    question: "Why did Omar say he passed his SSCE by no means a small feat?",
    section: 'This question is based on "The Life Changer" novel.',
    option: {
      a: "all of the above",
      b: "because he failed other subjects but passed maths and English",
      c: "because he registered with one of the miracle centers",
      d: "Because he passed excellently on his first attempt",
    },
    questionNub: 12,
    hasPassage: 0,
    category: "the-life-changer",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 13,
    question:
      "Who among Salma's roommate was reserved and withdrawn yet generous to a fault?",
    section: 'This question is based on "The Life Changer" novel.',
    option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
    questionNub: 13,
    hasPassage: 0,
    category: "the-life-changer",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 14,
    question: "Ummi is an Arabic word that is directly translated to mean_____",
    section: 'This question is based on "The Life Changer" novel.',
    option: {
      a: "My mom",
      b: "My mother",
      c: "grandmother",
      d: "Godmother",
    },
    questionNub: 14,
    hasPassage: 0,
    category: "the-life-changer",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
  {
    id: 15,
    question:
      "In Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______",
    section: 'This question is based on "The Life Changer" novel.',
    option: {
      a: "the Hakimi",
      b: "the high priest",
      c: "the governor",
      d: "community oracle",
    },
    questionNub: 15,
    hasPassage: 0,
    category: "the-life-changer",
    image: "",
    answer: "",
    solution: "",
    examtype: "utme",
    examyear: "2023",
  },
];

export const addEng1: QuestionData[] = [];
