export const english2023 = {
  questions: [
    {
      questions: [
        {
          id: 0,
          question: "battle",
          section: "",
          option: { a: "raffle", b: "latter", c: "bitter", d: "kettle" },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          section: "",
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          section: "",
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
  ],
};

export const english2023SecondBatch = {
  questions: [
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: "nak<ins>e</ins>d",
          section:
            "Choose the option that has the same vowel sound as the one represented by the letter[s] underlined.",
          option: { a: "friend", b: "bead", c: "fed", d: "bid" },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the word that has the same rhyme scheme as the word below:<br>\nDay",
          section: "",
          option: { a: "Dare", b: "Anime", c: "Flight", d: "Ball" },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question: "Pick out the option with a different rhyme",
          section: "",
          option: { a: "Roar", b: "Four", c: "Growl", d: "Bore" },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question: "battle",
          section:
            "Choose the word that has the same rhyme scheme as the following word:",
          option: { a: "raffle", b: "latter", c: "bitter", d: "kettle" },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          section: "",
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          section: "",
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "the-sound-system",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          section: "",
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          section: "",
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question: "Smoo[th]",
          section:
            "Choose the word that has the same consonant sound as the one in bracket.",
          option: { a: "worth", b: "dress", c: "brother", d: "wealthy" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "Choose the word which has the same consonant sounds as the underlined letter(s)<br>\nplea<ins>s</ins>ure",
          section: "",
          option: { a: "rejoice", b: "surge", c: "seizure", d: "reassure" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the option that has the same consonant sound as the one provided<br>\n/θ/",
          section: "",
          option: { a: "without", b: "health", c: "mouth", d: "neither" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nmar<ins>ks</ins>",
          section: "",
          option: { a: "exhaust", b: "axe", c: "mosque", d: "exist" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            "It is <ins>inconceivable</ins> that the cat devoured the cat.",
          section:
            "In this question, choose the option opposite in meaning to the underlined word or phrase.",
          option: {
            a: "unimaginable",
            b: "contestable",
            c: "incomprehensible",
            d: "credible",
          },
          topic: "antonyms-synonyms-homonyms",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "From the list of words letter A to D, choose the one that is most nearly opposite in meaning to the underlined word and that will, at the same time, correctly fill the gap in the sentence.<br>\n<br>\nEating fresh fruits and vegetables is <ins>beneficial</ins> to one's health while eating processed foods is ......",
          section:
            "In this question, choose the option opposite in meaning to the underlined word or phrase.",
          option: { a: "worrying", b: "painful", c: "tasteless", d: "harmful" },
          topic: "antonyms-synonyms-homonyms",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the option that is nearest in meaning to the underlined word(s)<br>\nIn Nigeria, it is a crime to <ins>plagiarize</ins> someone else's work.",
          section:
            "In this question, choose the option opposite in meaning to the underlined word or phrase.",
          option: { a: "initiate", b: "pirate", c: "compose", d: "desecrate" },
          topic: "antonyms-synonyms-homonyms",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
  ],
};

export const english2023ThirdBatch = {
  questions: [
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nmar<ins>ks</ins>",
          section: "",
          option: { a: "exhaust", b: "axe", c: "mosque", d: "exist" },
          topic: "consonants",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nSalma stayed at the most coveted and famous ______ hostel.',
          section: "",
          option: {
            a: "Queen Amina",
            b: "Queen Moremi",
            c: "Queen Lateefat",
            d: "Queen Haneefat",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho called the attention of the district head when it was discovered that Talle buys more than he could consume from the supermarket?',
          section: "",
          option: {
            a: "his friends",
            b: "the grocers",
            c: "His neighbors",
            d: "his colleagues",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nHow old is Bint?',
          section: "",
          option: {
            a: "5years old",
            b: "10years old",
            c: "8years old",
            d: "7years old",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_____ was always on the first row during prayer at his office.',
          section: "",
          option: { a: "Ahmed", b: "Zaki", c: "Habeeb", d: "Talle" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWhy did Habib call Tomiwa instead of Salma that he gave a ride?',
          section: "",
          option: {
            a: "Because Tomiwa is a Muslim and Salma is not",
            b: "Because Salma gave him Tomiwa's number instead of hers",
            c: "All of the above",
            d: "Because Habib likes Tomiwa more than Salma",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question: "...9...<br>\n&nbsp;",
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "modified",
            b: "regulated",
            c: "standardized",
            d: "ordered",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: "...10...",
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: { a: "a Decree", b: "bill", c: "an Act", d: "a motion" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nBint was encouraged to take French at the primary level because _____',
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "Her parents believed that language acquisition at an early age is relatively easy",
            b: "she would want to be a French mistress when she grows up",
            c: "all of the above",
            d: "it will be useful for her when she travels to France",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWhat appellation was given to Talle for all his amazing show of personality.',
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "The cool and calm one",
            b: "the moody ones",
            c: "the simple and delicate one",
            d: "the quiet one",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWhose reticent nature while growing up earned him the title: "The quiet one".?',
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: { a: "Talle", b: "Bint", c: "Omar", d: "Ummi" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nSalma was looking more stunning on the last day of her exams because_______',
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "her classmates had planned to go to the beach after the exam",
            b: "her classmates had organized a mini picnic to wrap up the good work",
            c: "All of the above",
            d: "her classmates had planned a photo shoot with some lecturers",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWhy was it a double celebration for Ummi and members of her community when she gained admission into the university?',
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "none of the above",
            b: "She had given birth to Omar before her admission to the university",
            c: "Her husband agreed to marry her before she went for university registration",
            d: "she was the first child to leave Lafayette to the university",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question: "...1...",
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: {
            a: "executive",
            b: "legislative",
            c: "judicial",
            d: "administrative",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question: "...2...",
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: { a: "modify", b: "nullify", c: "order", d: "enforce" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question: "...3...",
          section:
            "The passage below has gaps. Immediately following each gap, four options are provided. Choose the most appropriate option for each gap.",
          option: { a: "an anchor", b: "a portion", c: "a wing", d: "an arm" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question: "Athens had _________ the Greek-states against Persians.",
          section:
            "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
          option: {
            a: "refused to help",
            b: "wanted to fight",
            c: "intervened on behalf",
            d: "given orders to fight",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "Darius took drastic steps to __________ the rebellious Athenians.",
          section:
            "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
          option: { a: "irritate", b: "weaken", c: "destroy", d: "calm" },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question: "&nbsp;Their participation _________to the Athenians.",
          section:
            "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
          option: {
            a: "gave hope",
            b: "gave honour",
            c: "gave comfort",
            d: "gave strength",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The people of Delos did not want to __________ the conquest of Greece",
          section:
            "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
          option: {
            a: "think about",
            b: "end",
            c: "encourage",
            d: "daydream about",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "The Athenians were__________ by some soldiers who arrived at Plataea",
          section:
            "Use the passage to answer the questions below<br>\nRead the passage carefully and answer the questions that follow:<br>\n<br>\nThe victory of the small Greek democracy of Athens over the mighty Persian Empire was furious because Athens had interceded for the other Greek city-states in revolt against Persian domination. In anger, the king sent an enormous army to defeat Athens. He thought it would take drastic steps to pacify the rebellious part of the empire.<br>\n<br>\nPersia was ruled by one man. In Athens, however, all citiens helped to rule. Emboldened&nbsp;by this participation, Athenians were prepared to die for their city-state. Perhaps this was the secret of the remarkable victory at the marathon, the Persians tried to fool some Greek city-states by claiming to have come in peace. The frightened city of Delos refused to believe this. Not wanting to abet the conquest of Greece, they fled from their city and did not return until the Persians had left. They were wise, for the president next conquered the city of Eritrea and captured its people.<br>\n<br>\nTiny&nbsp;Athens stood alone against Persia. The Athenian people to their sanctuaries. There they prayed for deliverance. They asked their gods to expedite their victory. The Athenians refurbished their weapons and moved to the plan of Marathon where their little band would meet the Persians. At the last moment, soldiers from Plataea reinforced the Athenian troops.<br>\n<br>\nThe Athenian army attacked and Greek citizens fought bravely. The power of the mighty Persians was offset by the love that the Athenians had for their city. Athenians defeated the Persians in both archery and combat. Greek soldiers seized Persian sheep&nbsp;and burned them and the Persians fled in terror. Herodotus, a famous historian, reports that 6400 Persians died, compared to only 192 Athenians.",
          option: {
            a: "held",
            b: "strengthened",
            c: "welcomed",
            d: "captured",
          },
          topic: "comprehension",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
  ],
};
