export const english2023 = {
  questions: [
    {
      questions: [
        {
          id: 0,
          question: "battle",
          section: "",
          option: { a: "raffle", b: "latter", c: "bitter", d: "kettle" },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          section: "",
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          section: "",
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "oral-english",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          section: "",
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          section: "",
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          section: "",
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          section: "",
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          section: "",
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "stress",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 0,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          section: "",
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          section: "",
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 2,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          section: "",
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 3,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          section: "",
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 4,
          question:
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          section: "",
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "the-life-changer",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
  ],
};
