const EnglishGrammar2023 = {
  questions: [
    {
      id: 1,
      question: [
        "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
      ],
      option: { a: "therefore", b: "despite", c: "however", d: "besides" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, fill each gap with the most appropriate option from the list provided.",
        "Without our relentless campaigns, we might ...... sure of victory in the race for the National Assembly.",
      ],
      option: {
        a: "be never",
        b: "never have been",
        c: "never had been",
        d: "have never be",
      },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, fill each gap with the most appropriate option from the list provided.",
        "We are all hungry; we ...... anything to eat since morning.",
      ],
      option: {
        a: "hadn't had",
        b: "never had",
        c: "haven't had",
        d: "didn't have",
      },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In the following question, choose the option that best completes the sentence.<br>\nThe guest would have arrived earlier but he was _______ in traffic.",
      ],
      option: { a: "held down", b: "held up", c: "held about", d: "held off" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "He was both a writer and a politician, but he was better ........ a singer",
      ],
      option: { a: "like", b: "to be", c: "as if", d: "as" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "Fill each gap with the most appropriate option from the list provided.<br>\nWe had to ..... the group headed by Taiwo.",
      ],
      option: { a: "sell out", b: "sell off", c: "sell up", d: "selled" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, choose the option that best completes the gap(s).",
        "The proprietor of our school with his administrator ------------ expected yesterday.",
      ],
      option: { a: "are", b: "is", c: "was", d: "were" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
  ],
};

const wordClasses2023 = {
  questions: [
    {
      id: 1,
      question: [
        "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
      ],
      option: { a: "therefore", b: "despite", c: "however", d: "besides" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "He was both a writer and a politician, but he was better ........ a singer",
      ],
      option: { a: "like", b: "to be", c: "as if", d: "as" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "Fill in the gap with the appropriate option:<br>\nChildren are not allowed in the park ...... dark.",
      ],
      option: { a: "at", b: "over", c: "after", d: "in" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
  ],
};
