const EnglishGrammar2023 = {
  questions: [
    {
      id: 1,
      question: [
        "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
      ],
      option: { a: "therefore", b: "despite", c: "however", d: "besides" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, fill each gap with the most appropriate option from the list provided.",
        "Without our relentless campaigns, we might ...... sure of victory in the race for the National Assembly.",
      ],
      option: {
        a: "be never",
        b: "never have been",
        c: "never had been",
        d: "have never be",
      },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, fill each gap with the most appropriate option from the list provided.",
        "We are all hungry; we ...... anything to eat since morning.",
      ],
      option: {
        a: "hadn't had",
        b: "never had",
        c: "haven't had",
        d: "didn't have",
      },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In the following question, choose the option that best completes the sentence.<br>\nThe guest would have arrived earlier but he was _______ in traffic.",
      ],
      option: { a: "held down", b: "held up", c: "held about", d: "held off" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "He was both a writer and a politician, but he was better ........ a singer",
      ],
      option: { a: "like", b: "to be", c: "as if", d: "as" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "Fill each gap with the most appropriate option from the list provided.<br>\nWe had to ..... the group headed by Taiwo.",
      ],
      option: { a: "sell out", b: "sell off", c: "sell up", d: "selled" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "In this question, choose the option that best completes the gap(s).",
        "The proprietor of our school with his administrator ------------ expected yesterday.",
      ],
      option: { a: "are", b: "is", c: "was", d: "were" },
      topic: "grammar",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
  ],
};

const wordClasses2023 = {
  questions: [
    {
      id: 1,
      question: [
        "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
      ],
      option: { a: "therefore", b: "despite", c: "however", d: "besides" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "He was both a writer and a politician, but he was better ........ a singer",
      ],
      option: { a: "like", b: "to be", c: "as if", d: "as" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
    {
      id: 1,
      question: [
        "Fill in the gap with the appropriate option:<br>\nChildren are not allowed in the park ...... dark.",
      ],
      option: { a: "at", b: "over", c: "after", d: "in" },
      topic: "word-classes",
      image: "",
      answer: "",
      solution: "",
      examtype: "utme",
      examyear: "2023",
    },
  ],
};

const test = {
  questions: [
    {
      questions: [
        {
          id: 1,
          question: [
            "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
          ],
          option: { a: "therefore", b: "despite", c: "however", d: "besides" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "Without our relentless campaigns, we might ...... sure of victory in the race for the National Assembly.",
          ],
          option: {
            a: "be never",
            b: "never have been",
            c: "never had been",
            d: "have never be",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "We are all hungry; we ...... anything to eat since morning.",
          ],
          option: {
            a: "hadn't had",
            b: "never had",
            c: "haven't had",
            d: "didn't have",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In the following question, choose the option that best completes the sentence.<br>\nThe guest would have arrived earlier but he was _______ in traffic.",
          ],
          option: {
            a: "held down",
            b: "held up",
            c: "held about",
            d: "held off",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "He was both a writer and a politician, but he was better ........ a singer",
          ],
          option: { a: "like", b: "to be", c: "as if", d: "as" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "Fill in the gap in the sentence&nbsp;below with the appropriate option:<br>\nPeter and Jane love each other ...... the difficulties they face.",
          ],
          option: { a: "therefore", b: "despite", c: "however", d: "besides" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "He was both a writer and a politician, but he was better ........ a singer",
          ],
          option: { a: "like", b: "to be", c: "as if", d: "as" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Fill in the gap with the appropriate option:<br>\nChildren are not allowed in the park ...... dark.",
          ],
          option: { a: "at", b: "over", c: "after", d: "in" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "In the following question, choose the option that best completes the sentence.<br>\nThe guest would have arrived earlier but he was _______ in traffic.",
          ],
          option: {
            a: "held down",
            b: "held up",
            c: "held about",
            d: "held off",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Fill each gap with the most appropriate option from the list provided.<br>\nWe had to ..... the group headed by Taiwo.",
          ],
          option: { a: "sell out", b: "sell off", c: "sell up", d: "selled" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "Without our relentless campaigns, we might ...... sure of victory in the race for the National Assembly.",
          ],
          option: {
            a: "be never",
            b: "never have been",
            c: "never had been",
            d: "have never be",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "We are all hungry; we ...... anything to eat since morning.",
          ],
          option: {
            a: "hadn't had",
            b: "never had",
            c: "haven't had",
            d: "didn't have",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "In this question, choose the option that best completes the gap(s).",
            "The proprietor of our school with his administrator ------------ expected yesterday.",
          ],
          option: { a: "are", b: "is", c: "was", d: "were" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: ["...1..."],
          option: {
            a: "executive",
            b: "legislative",
            c: "judicial",
            d: "administrative",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: ["...2..."],
          option: { a: "modify", b: "nullify", c: "order", d: "enforce" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: ["...3..."],
          option: { a: "an anchor", b: "a portion", c: "a wing", d: "an arm" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: ["...4..."],
          option: {
            a: "Judiciary",
            b: "Executive Council",
            c: "House of Representatives",
            d: "National Assembly",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: ["...5..."],
          option: {
            a: "plaintiff",
            b: "attorney",
            c: "defendant",
            d: "litigant",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: [
            "From the list of words in A to D, choose one that best describes the sentence.<br>\nJames and Henry were at daggers drawn when I knew them. This means that they",
          ],
          option: {
            a: "were always angry with each other",
            b: "always wore daggers",
            c: "were good at drawing daggers",
            d: "were fighting everybody",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the interpretation that you consider most appropriate for each sentence.<br>\n<br>\nWhat I told you is the gospel truth. This means that the information is",
          ],
          option: {
            a: "unconfirmed",
            b: "partly true",
            c: "false",
            d: "completely true",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "Choose the word that has the same rhyme scheme as the following word:",
            "battle",
          ],
          option: { a: "raffle", b: "latter", c: "bitter", d: "kettle" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          ],
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          ],
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          ],
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          ],
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "Choose the word that has the same rhyme scheme as the following word:",
            "battle",
          ],
          option: { a: "raffle", b: "latter", c: "bitter", d: "kettle" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          ],
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          ],
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          ],
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          ],
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "Choose the option that has the same vowel sound as the one represented by the letter[s] underlined.",
            "nak<ins>e</ins>d",
          ],
          option: { a: "friend", b: "bead", c: "fed", d: "bid" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the option that has the same vowel sound as the letter(s) underlined<br>\n<br>\n<ins>e</ins>xist",
          ],
          option: { a: "never", b: "isle", c: "meant", d: "helicopter" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the word that does not have the same vowel sound as the others",
          ],
          option: { a: "shun", b: "son", c: "sun", d: "short" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the option that has the same vowel sound as the one represented by the letter(s) underlined<br>\nc<ins>a</ins>sualty",
          ],
          option: { a: "sure", b: "amateur", c: "juice", d: "aesthetic" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "Choose the word that has the same CONSONANT SOUND as the one represented by the letter(s) underlined.<br>\nwa<ins>sh</ins>",
          ],
          option: { a: "treasure", b: "occasion", c: "nation", d: "equation" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "From the words lettered A to D, choose the word that has the same consonant sound(s) as the one represented by the letter(s) underlined below.<br>\n<br>\n<ins>P</ins>in",
          ],
          option: {
            a: "Psychology",
            b: "Pneumonia",
            c: "Pseudonym",
            d: "Pragmatic",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the word that has the same consonant sound as the one in bracket.",
            "Smoo[th]",
          ],
          option: { a: "worth", b: "dress", c: "brother", d: "wealthy" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the word which has the same consonant sounds as the underlined letter(s)<br>\nplea<ins>s</ins>ure",
          ],
          option: { a: "rejoice", b: "surge", c: "seizure", d: "reassure" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the option that has the same consonant sound as the one provided<br>\n/θ/",
          ],
          option: { a: "without", b: "health", c: "mouth", d: "neither" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: [
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          ],
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          ],
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the appropriate stress pattern from the options.The stressed words are in capital letter(s)<br>\nFluency",
          ],
          option: {
            a: "flu-EN-cy",
            b: "flu-en-CY",
            c: "flu-en-cy",
            d: "FLU-en-cy",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "The primary stress is indicated by writing the syllable on which it occurs in capital letters. From the words lettered A to D choose the one that has the correct stress.<br>\ncategory",
          ],
          option: {
            a: "cat-e-GO-ry",
            b: "CAT-e-go-ry",
            c: "cat-e-go-RY",
            d: "cat-E-go-ry",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          ],
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            "The words in capital letter have the emphatic stress. Choose the options to which the given sentences relate.<br>\nI bought my WIFE a red dress",
          ],
          option: {
            a: "Did I buy my husband a red dress?",
            b: "Did I buy my wife a red shoe?",
            c: "Did he buy my wife a red dress?",
            d: "Did I buy my wife a black dress?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the following sentences, the word that resolves the emphatic stress is written in capital letters. From the options letters A to D, choose the one to which the given sentence is the appropriate answer.<br>\n<br>\nDaddy plays TENNIS on Saturday afternoons",
          ],
          option: {
            a: "Does mummy play tennis on Saturday afternoons?",
            b: "Does daddy play tennis on Sunday afternoons?",
            c: "Does daddy play tennis on Saturday morning?",
            d: "Does daddy play cricket on Saturday afternoon?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Choose the options to which the given sentence relate.<br>\n<br>\nSpain won their last friendly FOOTBALL match",
          ],
          option: {
            a: "Who won their last friendly football match?",
            b: "Did Spain win their last competitive football match",
            c: "Did Spain lose their last competitive football match",
            d: "Did Spain win their last friendly basketball match?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the questions, the word in capital letters has the emphatic stress. Choose the option to which the given sentence relates.The union congratulated the ELECTED president.",
          ],
          option: {
            a: "Did the union reject the elected president?",
            b: "Did the union congratulate the elected chairman?",
            c: "Did the management congratulate the elected president?",
            d: "Did the union congratulate the ousted president?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In each of the questions, the word in capital letters has the emphatic stress. Choose the option to which the given sentence relates.A good description INCLUDES specific nouns.",
          ],
          option: {
            a: "Does a good description exclude specific nouns?",
            b: "Does a good description include specific verbs?",
            c: "Does a good description include obscure nouns?",
            d: "Does a poor description include specific nouns?",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    {
      questions: [
        {
          id: 1,
          question: [
            'This question is based on "The Life Changer" novel.<br>\n<br>\n_________ is the euphemism use for Cheat notes.',
          ],
          option: {
            a: "Salvation note of rescue",
            b: "note of deliverance",
            c: "holy note of rescue",
            d: "Notes of salvation",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            'This question is based on "The Life Changer" novel.<br>\n<br>\nwhy did Omar say he passed his SSCE by no means a small feat?',
          ],
          option: {
            a: "all of the above",
            b: "because he failed other subjects but passed maths and English",
            c: "because he registered with one of the miracle centers",
            d: "Because he passed excellently on his first attempt",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            'This question is based on "The Life Changer" novel.<br>\n<br>\nWho among Salma\'s roommate was reserved and withdrawn yet generous to a fault?',
          ],
          option: { a: "Ngozi", b: "Tomiwa", c: "Ada", d: "none of them" },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            'This question is based on "The Life Changer" novel.<br>\n<br>\nUmmi is an Arabic word that is directly translated to mean_____',
          ],
          option: {
            a: "My mom",
            b: "My mother",
            c: "grandmother",
            d: "Godmother",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            'This question is based on "The Life Changer" novel.<br>\n<br>\nIn Lafayette, before a stranger is hosted or accommodated, permission must be requested and granted by_______',
          ],
          option: {
            a: "the Hakimi",
            b: "the high priest",
            c: "the governor",
            d: "community oracle",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: [
            "In this question, select the option that best explains the information conveyed in the sentence.",
            "If he were here, it could be more fun.",
          ],
          option: {
            a: "He did not show up and so the occasion lacked much fun",
            b: "He was expected but did not show up to liven up the occasion",
            c: "There was no fun because he was not present",
            d: "He was being expected to supply more fun",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, select the option that best explains the information conveyed in the sentence.",
            "Though he is our elected representative, he often takes a rather jaundiced view of our problems.",
          ],
          option: {
            a: "He takes a rather hazy view of our problems",
            b: "He takes an unfavourable position concerning our problems",
            c: "He takes a rather forceful view of our problems",
            d: "He takes a sickly view of our problems",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "From the list of words in A to D, choose one that best describes the sentence.<br>\nJames and Henry were at daggers drawn when I knew them. This means that they",
          ],
          option: {
            a: "were always angry with each other",
            b: "always wore daggers",
            c: "were good at drawing daggers",
            d: "were fighting everybody",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, select the option that best explains the information conveyed in the sentence.",
            "The solution lies in choosing between various negative alternatives.",
          ],
          option: {
            a: "The solutions are many",
            b: "The solution lies in choosing between the positive and negative",
            c: "The solution can be found in one of the negative options",
            d: "The solution is a negative one",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "Select the option that best explains the information conveyed in the sentence.<br>\n<br>\nThe stadium had a capacity crowd in spite of the weather.",
          ],
          option: {
            a: "The stadium was not filled because of the weather",
            b: "The crowd defied the weather to fill the stadium",
            c: "The crowd loved the weather at the stadium",
            d: "The weather favoured the crowd at the stadium",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
    {
      questions: [
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "Without our relentless campaigns, we might ...... sure of victory in the race for the National Assembly.",
          ],
          option: {
            a: "be never",
            b: "never have been",
            c: "never had been",
            d: "have never be",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
        {
          id: 1,
          question: [
            "In this question, fill each gap with the most appropriate option from the list provided.",
            "We are all hungry; we ...... anything to eat since morning.",
          ],
          option: {
            a: "hadn't had",
            b: "never had",
            c: "haven't had",
            d: "didn't have",
          },
          topic: "word-classes",
          image: "",
          answer: "",
          solution: "",
          examtype: "utme",
          examyear: "2023",
        },
      ],
    },
    { questions: [] },
  ],
};
